version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER            : pato
  MYSQL_PASSWORD        : duck
  # pw for root superuser
  MYSQL_ROOT_PASSWORD   : root
  MYSQL_DATABASE        : job
  REACT_APP_SERVER_PORT : 8000

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: ./.env
    environment:
      # <<: *common-variables
      MYSQL_HOST            : ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD   : ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER            : ${MYSQL_USER} 
      MYSQL_PASSWORD        : ${MYSQL_PASSWORD} 
      MYSQL_DATABASE        : $MYSQL_DATABASE
      REACT_APP_SERVER_PORT : $REACT_APP_SERVER_PORT
    ports:
      - 3306:3306
    restart: unless-stopped
    # Load database from disc
    volumes:
      - ./sqldb/backup_job.sql:/docker-entrypoint-initdb.d/sample.sql
  
  server:
    build: ./server
    container_name: server
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP : mysql
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: npm start
  
  fe:
    build: ./fe
    container_name: fe
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./fe/src:/app/src
    links:
      - server
    command: npm start
